export const kinnAbi = [
  "function getVault(address owner) view returns ((address owner,uint64 lastCheckIn,uint64 checkInInterval,uint8 maxMissedCheckIns,bool active,bool inheritanceTriggered,uint128 automationReserve))",
  "function getBeneficiaries(address owner) view returns ((address account,uint16 allocationBps)[])",
  "function getTokenBalance(address owner,address token) view returns (uint256)",
  "function getVaultTokens(address owner) view returns (address[])",
  "function nextExpectedCheckIn(address owner) view returns (uint256)",
  "function missedCheckIns(address owner) view returns (uint8)",
  "function inheritanceEligible(address owner) view returns (bool)",
  "function getPendingInheritance(address owner,address token,address beneficiary) view returns (uint256)",
  "function getNextDistributionRetry(address owner,address token,address beneficiary) view returns (uint256)",
  "function inheritanceTokenProcessed(address owner,address token) view returns (bool)",
  "function automationReserve(address owner) view returns (uint256)",
  "function automationFeeWei() view returns (uint256)",
  "function createVault(uint64 checkInInterval,uint8 maxMissedCheckIns,address[] accounts,uint16[] allocationsBps)",
  "function topUpAutomationReserve() payable",
  "function withdrawAutomationReserve(uint256 amount)",
  "function claimCompletedAutomationReserve(address owner)",
  "function updateSettings(uint64 checkInInterval,uint8 maxMissedCheckIns)",
  "function updateBeneficiaries(address[] accounts,uint16[] allocationsBps)",
  "function deposit(address token,uint256 amount)",
  "function withdraw(address token,uint256 amount)",
  "function closeVault()",
  "function checkIn()",
  "function triggerInheritance(address owner)",
  "function distributeInheritanceToken(address owner,address token)",
  "function retryInheritanceDistribution(address owner,address token,address beneficiary)",
  "event VaultCreated(address indexed owner,uint64 checkInInterval,uint8 maxMissedCheckIns,uint64 lastCheckIn)",
  "event AssetDeposited(address indexed owner,address indexed token,uint256 amount)",
  "event AssetWithdrawn(address indexed owner,address indexed token,uint256 amount)",
  "event CheckedIn(address indexed owner,uint64 timestamp)",
  "event InheritanceTriggered(address indexed owner,address indexed executor,uint64 timestamp)",
  "event InheritanceTokenProcessed(address indexed owner,address indexed token,uint256 amount)",
  "event InheritanceDistributed(address indexed owner,address indexed token,address indexed beneficiary,uint256 amount)",
  "event InheritanceDistributionFailed(address indexed owner,address indexed token,address indexed beneficiary,uint256 amount,uint256 nextRetryAt)"
] as const;
